<script setup lang="ts">
const route=useRoute(),{me,api}=useShowUp()
const data=ref<any>()
const { loading, refreshError, refresh } = useLiveRefresh(async () => { data.value = me.value ? await api(`/api/reservations/${route.params.reservationId}`) : null })
const items=computed(()=>data.value?.history?.map((h:any)=>({label:h.action.replaceAll('_',' ').toLowerCase(),detail:new Date(h.at).toLocaleString(),done:h.outcome==='ACCEPTED',level:h.outcome==='ACCEPTED'?'Recorded':'Rejected'}))||[])
function exportReceipt() {
  const url = URL.createObjectURL(new Blob([JSON.stringify({ schemaVersion:1, network:'Nimiq Testnet', exportedAt:new Date().toISOString(), ...data.value }, null, 2)], {type:'application/json'}))
  const link = document.createElement('a'); link.href=url; link.download=`showup-receipt-${route.params.reservationId}.json`
  document.body.appendChild(link); link.click(); link.remove(); setTimeout(()=>URL.revokeObjectURL(url),1000)
}
</script>
<template><div class="shell"><AppHeader/><div class="page-head"><p>Receipt</p><h1>What happened, in order.</h1><p>Financial status comes from the server and verified Nimiq testnet evidence.</p></div><StatusNotice v-if="refreshError" tone="error" title="Refresh unavailable" :message="refreshError"/><EmptyState v-if="!me" title="Connect your wallet" message="Receipts are private to the participant and operator."><WalletButton/></EmptyState><div v-else-if="loading" class="skeleton"/><main v-else-if="data"><ReservationPass :event="data.reservation" :reservation="data.reservation"/><section class="panel"><h2>Evidence timeline</h2><StatusTimeline :items="items"/></section><section class="panel"><h2>Settlement</h2><StatusNotice v-for="refund in data.refunds" :key="refund.id" :tone="refund.state==='SETTLED'?'success':'waiting'" :title="refund.state==='SETTLED'?'Refund verified':'Refund '+refund.state.toLowerCase()" :message="refund.reason.replaceAll('_',' ').toLowerCase()"/><p v-if="!data.refunds.length">{{ data.reservation.settlement_state==='TICKET_CONSUMED'?'Admission completed. This ticket does not include a check-in refund.':'No refund obligation has been created.' }}</p><EvidenceDisclosure title="View technical evidence" :evidence="data.evidence"/><button class="secondary" @click="refresh">Refresh status</button><p>The export contains private wallet and transaction details. Share it only with people you trust.</p><button class="secondary" @click="exportReceipt">Export private receipt</button></section></main><EmptyState v-else title="Receipt unavailable" message="This receipt is not available to the connected wallet."/></div></template>
